name: UI Tests - Smoke | Regression

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

  pull_request:

  workflow_dispatch:
      inputs:
        test_type:
          description: "Tipo de tests a ejecutar"
          required: true
          default: "smoke"
          type: choice
          options:
            - smoke
            - regression

defaults:
  run:
    working-directory: .

jobs:
  smoke-tests:
    name: UI Tests - Smoke
    runs-on: ubuntu-latest

    # Push (local) → corre smoke (default) + allure | Ejecución manual + smoke (CI) → solo smoke + allure
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'smoke'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke tests
        run: pytest tests/smoke -m smoke --alluredir=reports/allure-results
        env:
          HEADLESS: true

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: reports/allure-results
  

  regression-tests:
    name: UI Tests - Regression
    runs-on: ubuntu-latest

    # Ejecución manual + regression (CI) → solo regression + allure
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.test_type == 'regression'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run regression tests
        run: pytest tests/regression -m regression --alluredir=reports/allure-results
        env:
          HEADLESS: true

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: allure-results-regression
           path: reports/allure-results
      

# GitHub: Se descargan los artefactos por separado - Se generan dos reportes distintos - Se publican ambos en Pages
# smoke-tests → produce allure-results-smoke

# regression-tests → produce allure-results-regression

# publish-allure → consume artifacts y publica

  publish-allure:
    name: Publish Allure Report
    runs-on: ubuntu-latest

    needs:
      - smoke-tests
      - regression-tests

    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      # Descarga los artefactos

      - name: Download Smoke Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-smoke
          path: artifacts/smoke
        continue-on-error: true

      - name: Download Regression Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-regression
          path: artifacts/regression
        continue-on-error: true


      # Instalación Java + Allure

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre

      - name: Install Allure
        run: |
          curl -L -o allure.tgz https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version
      

      # Generarión de reportes

      - name: Generate Allure Reports
        run: |
          mkdir -p public/smoke public/regression
          
          if [ -d artifacts/smoke ]; then
            allure generate artifacts/smoke --clean -o public/smoke || true
          fi
          
          if [ -d artifacts/regression ]; then
            allure generate artifacts/regression --clean -o public/regression || true
          fi
      

      # Creación index.html raíz para smoke y regression

      - name: Create index.html
        run: |
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <title>Allure Reports</title>
          </head>
          <body>
            <h1>Allure Reports</h1>
            <ul>
              <li><a href="smoke/">Smoke Tests</a></li>
              <li><a href="regression/">Regression Tests</a></li>
            </ul>
          </body>
          </html>
          EOF
      

      # Publicación en GitHub Pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public